import type { CSSProperties } from "react";

export function buildFollowupPanelStyles(isDark: boolean) {
  const toolbarBlack = {
    panel: "#060d08",
    panelBorder: "rgba(255, 255, 255, 0.08)",
    text: "#e5e7eb",
    textMuted: "#9ca3af",
    buttonBg: "#141414",
    buttonBorder: "rgba(255, 255, 255, 0.12)",
    divider: "rgba(255, 255, 255, 0.1)",
  };

  return {
    panelStyle: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
      flex: 1,
      minHeight: 0,
      height: "100%",
      overflow: "hidden",
    } satisfies CSSProperties,
    toolbarStyle: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
      padding: "10px 12px",
      background: isDark ? toolbarBlack.panel : "#ffffff",
      border: isDark ? `1px solid ${toolbarBlack.panelBorder}` : "1px solid #dcebd8",
      borderRadius: 12,
      boxShadow: isDark ? "0 4px 16px rgba(0, 0, 0, 0.45)" : "0 2px 8px rgba(11, 34, 16, 0.06)",
      flexShrink: 0,
    } satisfies CSSProperties,
    metaColumn: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
      flex: "1 1 240px",
      minWidth: 0,
    } satisfies CSSProperties,
    janelaRow: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 8,
      rowGap: 4,
      paddingTop: 6,
      borderTop: isDark ? `1px solid ${toolbarBlack.divider}` : "1px solid #eef5ec",
    } satisfies CSSProperties,
    statusPill: {
      display: "inline-flex",
      alignItems: "center",
      fontSize: 10,
      fontWeight: 700,
      lineHeight: 1.2,
      padding: "3px 8px",
      borderRadius: 999,
      border: "1px solid",
      whiteSpace: "nowrap",
    } satisfies CSSProperties,
    metaHint: {
      fontSize: 10,
      lineHeight: 1.35,
      color: isDark ? toolbarBlack.textMuted : "#6b8a76",
      flex: "1 1 180px",
      minWidth: 0,
    } satisfies CSSProperties,
    metaItem: {
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      fontSize: 11.5,
      color: isDark ? toolbarBlack.textMuted : "#5d7a67",
    } satisfies CSSProperties,
    metaStrong: {
      color: isDark ? toolbarBlack.text : "#0b2210",
      fontWeight: 700,
    } satisfies CSSProperties,
    metaDivider: {
      width: 1,
      height: 18,
      background: isDark ? toolbarBlack.divider : "#dcebd8",
      flexShrink: 0,
    } satisfies CSSProperties,
    toolButtonStyle: {
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      background: isDark ? toolbarBlack.buttonBg : "#f4faf2",
      color: isDark ? toolbarBlack.text : "#2d4a35",
      border: isDark ? `1px solid ${toolbarBlack.buttonBorder}` : "1px solid #b8d4bc",
      borderRadius: 8,
      padding: "6px 10px",
      fontSize: 11.5,
      fontWeight: 600,
      lineHeight: 1.1,
      cursor: "pointer",
    } satisfies CSSProperties,
    validationBadge: {
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      fontSize: 10.5,
      fontWeight: 700,
      border: "1px solid",
      borderRadius: 20,
      padding: "4px 9px",
    } satisfies CSSProperties,
    saveButtonStyle: {
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      border: isDark ? "1px solid rgba(255, 255, 255, 0.14)" : "1px solid #90caf9",
      background: isDark ? "#1a1a1a" : "#e3f2fd",
      color: isDark ? "#d1d5db" : "#1565c0",
      borderRadius: 8,
      padding: "6px 10px",
      fontSize: 11,
      fontWeight: 700,
      cursor: "pointer",
    } satisfies CSSProperties,
    saveAndCloseButtonStyle: {
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      border: isDark ? "1px solid rgba(255, 255, 255, 0.14)" : "1px solid #a5d6a7",
      background: isDark ? "#1a1a1a" : "#e8f5e9",
      color: isDark ? "#d1d5db" : "#2e7d32",
      borderRadius: 8,
      padding: "6px 10px",
      fontSize: 11,
      fontWeight: 700,
      cursor: "pointer",
    } satisfies CSSProperties,
    canvasWrapper: {
      width: "100%",
      flex: 1,
      minHeight: 420,
      display: "flex",
      flexDirection: "column",
      position: "relative",
      overflow: "hidden",
      borderRadius: 12,
      border: "1px solid #dcebd8",
      background: "#f8faf8",
    } satisfies CSSProperties,
  };
}

export const followupToolbarGroup: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  flexWrap: "wrap",
  gap: 6,
};
