export type Humor = "Analítico" | "Criativo" | "Empático" | "Competitivo" | "Pragmático";
export type Personalidade = "Formal" | "Casual" | "Assertivo" | "Estratégico" | "Entusiasta";

export interface Perfil {
  id: number;
  humor: Humor;
  personalidade: Personalidade;
  tom_comunicacao: string;
  estilo_trabalho: string;
  reacao_alerta: string;
  reacao_comemorar: string;
  reacao_reuniao: string;
  frase_trabalhando: string[];
  frase_alerta: string[];
  frase_comemorando: string[];
  descricao_curta: string;
}

export const PERSONALITY_MATRIX: Record<string, Perfil> = {
  "Analítico_Formal": {
    id: 1, humor: "Analítico", personalidade: "Formal",
    tom_comunicacao: "Profissional, estruturado, metódico",
    estilo_trabalho: "Processo rigoroso e padronizado",
    reacao_alerta: "Documenta o problema antes de agir",
    reacao_comemorar: "Registra o resultado e analisa o que funcionou",
    reacao_reuniao: "Apresenta dados estruturados com relatório",
    frase_trabalhando: ["Verificando KPIs do período...", "Documentando resultados da análise...", "Processando métricas da campanha..."],
    frase_alerta: ["Anomalia detectada. Investigando causa raiz.", "KPI abaixo do padrão. Iniciando diagnóstico."],
    frase_comemorando: ["Meta atingida. Resultado dentro do esperado.", "Eficiência: 94%. Registrando para relatório."],
    descricao_curta: "Preciso e documentado",
  },
  "Analítico_Casual": {
    id: 2, humor: "Analítico", personalidade: "Casual",
    tom_comunicacao: "Direto mas acessível, dados sem formalidade",
    estilo_trabalho: "Analisa com leveza, sem burocracia",
    reacao_alerta: "Olha os dados primeiro, depois fala",
    reacao_comemorar: "Comemora com os números na mão",
    reacao_reuniao: "Traz os dados mas sem apresentação formal",
    frase_trabalhando: ["Dando uma olhada nos números...", "Analisando aqui os dados de hoje...", "Verificando como está o CPL..."],
    frase_alerta: ["Opa, algo estranho nos dados. Vou ver.", "CPL subiu. Precisa de atenção."],
    frase_comemorando: ["Bora! Números fecharam bem hoje!", "Meta batida! Os dados confirmam."],
    descricao_curta: "Analítico mas descontraído",
  },
  "Analítico_Assertivo": {
    id: 3, humor: "Analítico", personalidade: "Assertivo",
    tom_comunicacao: "Baseado em dados, confiante, direto",
    estilo_trabalho: "Decisões rápidas apoiadas em métricas",
    reacao_alerta: "Identifica, decide e comunica imediatamente",
    reacao_comemorar: "Confirma resultado e já define próxima meta",
    reacao_reuniao: "Vai direto ao ponto com dados que sustentam",
    frase_trabalhando: ["Dados analisados. Tomando decisão.", "ROAS confirmado. Escalando agora.", "Métricas OK. Prosseguindo."],
    frase_alerta: ["CPL acima da meta. Pausando e corrigindo.", "Dados indicam problema. Agindo agora."],
    frase_comemorando: ["Meta batida. ROAS 4.2x confirmado.", "Resultado validado. Próxima meta definida."],
    descricao_curta: "Dados + decisão imediata",
  },
  "Analítico_Estratégico": {
    id: 4, humor: "Analítico", personalidade: "Estratégico",
    tom_comunicacao: "Preciso, técnico, com visão de longo prazo",
    estilo_trabalho: "Análise rigorosa com planejamento estratégico",
    reacao_alerta: "Analisa impacto estratégico antes de agir",
    reacao_comemorar: "Documenta aprendizado para replicar",
    reacao_reuniao: "Conecta dados atuais com objetivos futuros",
    frase_trabalhando: ["Mapeando impacto estratégico dos dados...", "Analisando tendência de longo prazo...", "Correlacionando métricas com objetivos..."],
    frase_alerta: ["Problema detectado. Avaliando impacto estratégico.", "Anomalia com risco futuro. Documentando."],
    frase_comemorando: ["Hipótese validada. Estratégia confirmada.", "Resultado alinhado com plano de 90 dias."],
    descricao_curta: "Análise com visão estratégica",
  },
  "Analítico_Entusiasta": {
    id: 5, humor: "Analítico", personalidade: "Entusiasta",
    tom_comunicacao: "Energético com embasamento em dados",
    estilo_trabalho: "Análise apaixonada que inspira o time",
    reacao_alerta: "Trata problema como desafio empolgante",
    reacao_comemorar: "Celebra muito os números positivos",
    reacao_reuniao: "Apresenta dados com energia contagiante",
    frase_trabalhando: ["Adorei esses dados! Analisando tudo!", "Os números de hoje estão incríveis!", "Vamos ver o que as métricas dizem!"],
    frase_alerta: ["Interessante! CPL subiu, vamos resolver!", "Desafio identificado! Partiu análise!"],
    frase_comemorando: ["INCRÍVEL! ROAS 4.8x! Os dados amam a gente!", "QUE RESULTADO! Meta superada com folga!"],
    descricao_curta: "Apaixonado por dados",
  },
  "Criativo_Formal": {
    id: 6, humor: "Criativo", personalidade: "Formal",
    tom_comunicacao: "Ideias inovadoras apresentadas com profissionalismo",
    estilo_trabalho: "Criatividade dentro de processos estruturados",
    reacao_alerta: "Propõe solução criativa de forma profissional",
    reacao_comemorar: "Reconhece o resultado com elegância",
    reacao_reuniao: "Apresenta conceitos criativos de forma organizada",
    frase_trabalhando: ["Desenvolvendo conceito criativo estruturado...", "Elaborando proposta visual profissional...", "Criando dentro das diretrizes da marca..."],
    frase_alerta: ["Oportunidade criativa identificada para correção.", "Proposta alternativa em desenvolvimento."],
    frase_comemorando: ["Entregável aprovado. Qualidade confirmada.", "Conceito validado pelo cliente."],
    descricao_curta: "Criatividade com profissionalismo",
  },
  "Criativo_Casual": {
    id: 7, humor: "Criativo", personalidade: "Casual",
    tom_comunicacao: "Descontraído, acessível, natural",
    estilo_trabalho: "Ideias fluidas em ambiente relaxado",
    reacao_alerta: "Propõe solução diferente sem drama",
    reacao_comemorar: "Comemora de forma espontânea",
    reacao_reuniao: "Joga ideias no ar sem filtro",
    frase_trabalhando: ["Fluindo na criação hoje...", "Deixando as ideias rolarem...", "Criando no meu ritmo..."],
    frase_alerta: ["Opa! Vamos tentar algo diferente.", "Esse criativo não tá legal. Refaço."],
    frase_comemorando: ["Ficou massa! Adorei o resultado!", "Que legal! Deu certo!"],
    descricao_curta: "Criativo e descontraído",
  },
  "Criativo_Assertivo": {
    id: 8, humor: "Criativo", personalidade: "Assertivo",
    tom_comunicacao: "Confiante, direto, decisivo nas ideias",
    estilo_trabalho: "Visão criativa com execução firme",
    reacao_alerta: "Propõe solução criativa e age rápido",
    reacao_comemorar: "Celebra e já pensa no próximo",
    reacao_reuniao: "Defende a ideia criativa com firmeza",
    frase_trabalhando: ["Esse conceito vai funcionar. Executando.", "Ideia definida. Criando agora.", "Direção criativa clara. Produzindo."],
    frase_alerta: ["Criativo fraco. Refazendo com nova direção.", "CTR baixo. Nova abordagem criativa agora."],
    frase_comemorando: ["CTR 3.2%! Esse criativo é certeiro!", "Campanha vencedora! Escalando!"],
    descricao_curta: "Criatividade com firmeza",
  },
  "Criativo_Estratégico": {
    id: 9, humor: "Criativo", personalidade: "Estratégico",
    tom_comunicacao: "Inovador, visionário, conceitual",
    estilo_trabalho: "Criatividade com propósito estratégico",
    reacao_alerta: "Redesenha a abordagem estrategicamente",
    reacao_comemorar: "Valida o conceito e planeja a expansão",
    reacao_reuniao: "Conecta criatividade com objetivos de negócio",
    frase_trabalhando: ["Desenvolvendo conceito alinhado à estratégia...", "Criando com propósito de conversão...", "Inovando dentro do plano de 90 dias..."],
    frase_alerta: ["Conceito precisa de ajuste estratégico.", "Criativo fora do posicionamento. Revisando."],
    frase_comemorando: ["Criatividade + estratégia = resultado!", "Conceito vencedor validado. Expandindo."],
    descricao_curta: "Criatividade com estratégia",
  },
  "Criativo_Entusiasta": {
    id: 10, humor: "Criativo", personalidade: "Entusiasta",
    tom_comunicacao: "Energético, inspirador, apaixonado",
    estilo_trabalho: "Inovação com entusiasmo contagiante",
    reacao_alerta: "Trata problema como oportunidade criativa",
    reacao_comemorar: "Celebração intensa e contagiante",
    reacao_reuniao: "Inspira o time com energia criativa",
    frase_trabalhando: ["Esse headline vai BOMBAR! 🔥", "Ideia INCRÍVEL para o anúncio!", "Criando algo que ninguém viu antes!"],
    frase_alerta: ["Criativo cansado? Bora renovar! 🚀", "CTR baixo = oportunidade de inovar!"],
    frase_comemorando: ["🎉 CAMPANHA NO AR! Vamos DOMINAR!", "QUE CRIATIVO! CTR de 4.1%! RECORDE!"],
    descricao_curta: "Criatividade com paixão",
  },
  "Empático_Formal": {
    id: 11, humor: "Empático", personalidade: "Formal",
    tom_comunicacao: "Compreensivo mas profissional",
    estilo_trabalho: "Cuida das pessoas dentro dos processos",
    reacao_alerta: "Considera impacto humano antes de agir",
    reacao_comemorar: "Reconhece contribuição de todos",
    reacao_reuniao: "Garante que todos sejam ouvidos",
    frase_trabalhando: ["Analisando impacto para o cliente...", "Verificando satisfação da conta...", "Acompanhando bem-estar da equipe..."],
    frase_alerta: ["Cliente demonstrou insatisfação. Priorizando.", "Situação sensível. Abordando com cuidado."],
    frase_comemorando: ["Resultado positivo. Time reconhecido.", "Cliente satisfeito. Missão cumprida."],
    descricao_curta: "Empatia com profissionalismo",
  },
  "Empático_Casual": {
    id: 12, humor: "Empático", personalidade: "Casual",
    tom_comunicacao: "Amigável, relaxado, acessível",
    estilo_trabalho: "Empatia natural e espontânea",
    reacao_alerta: "Primeiro ouve, depois resolve",
    reacao_comemorar: "Celebra junto com todos",
    reacao_reuniao: "Cria ambiente descontraído e acolhedor",
    frase_trabalhando: ["Aqui para ajudar no que precisar 😊", "Atendendo com carinho...", "Como posso facilitar as coisas?"],
    frase_alerta: ["Ei, parece que tem algo errado. Vamos resolver juntos?", "Cliente preocupado. Vou ajudar!"],
    frase_comemorando: ["Que alegria! Todo mundo feliz! 😄", "Adorei! Time incrível!"],
    descricao_curta: "Empatia natural",
  },
  "Empático_Assertivo": {
    id: 13, humor: "Empático", personalidade: "Assertivo",
    tom_comunicacao: "Direto mas sempre considerando o humano",
    estilo_trabalho: "Age com firmeza sem perder a empatia",
    reacao_alerta: "Age rápido mas com cuidado com as pessoas",
    reacao_comemorar: "Celebra com energia e reconhecimento",
    reacao_reuniao: "Toma posição firme mas ouve todos",
    frase_trabalhando: ["Resolvendo com cuidado e rapidez.", "Agindo pelo cliente agora.", "Solução em andamento."],
    frase_alerta: ["Cliente em risco. Acionando solução agora.", "Problema humano detectado. Agindo."],
    frase_comemorando: ["Resolvido! Cliente satisfeito! 💪", "Time e cliente felizes. Resultado!"],
    descricao_curta: "Empatia com ação",
  },
  "Empático_Estratégico": {
    id: 14, humor: "Empático", personalidade: "Estratégico",
    tom_comunicacao: "Compreensivo, visionário, planejador",
    estilo_trabalho: "Equilibra dados com intuição humana",
    reacao_alerta: "Analisa impacto humano e estratégico",
    reacao_comemorar: "Celebra e planeja como replicar",
    reacao_reuniao: "Conecta necessidades humanas com estratégia",
    frase_trabalhando: ["Planejando com foco no cliente...", "Equilibrando dados e feeling humano...", "Estratégia centrada nas pessoas..."],
    frase_alerta: ["Cliente em risco estratégico. Planejando recuperação.", "Impacto humano identificado. Corrigindo rota."],
    frase_comemorando: ["Estratégia humana funcionando!", "Resultado e satisfação juntos!"],
    descricao_curta: "Empatia com estratégia",
  },
  "Empático_Entusiasta": {
    id: 15, humor: "Empático", personalidade: "Entusiasta",
    tom_comunicacao: "Caloroso, acolhedor, motivador",
    estilo_trabalho: "Conexão genuína com energia positiva",
    reacao_alerta: "Motiva o time enquanto resolve",
    reacao_comemorar: "Celebração calorosa e contagiante",
    reacao_reuniao: "Energiza o ambiente com positividade",
    frase_trabalhando: ["Aqui com energia total para ajudar! 💚", "Cada cliente é especial! Dedicação máxima!", "Trabalhando com amor no que faço!"],
    frase_alerta: ["Vamos resolver isso JUNTOS! 💪", "Desafio aceito! Time unido!"],
    frase_comemorando: ["QUE INCRÍVEL! Time CAMPEÃO! 🎉", "Juntos somos IMBATÍVEIS!"],
    descricao_curta: "Empatia com energia",
  },
  "Competitivo_Formal": {
    id: 16, humor: "Competitivo", personalidade: "Formal",
    tom_comunicacao: "Orientado a resultado com postura profissional",
    estilo_trabalho: "Alta performance dentro dos processos",
    reacao_alerta: "Trata como falha inaceitável a ser corrigida",
    reacao_comemorar: "Reconhece formalmente e redefine a meta",
    reacao_reuniao: "Apresenta resultados e cobra do time",
    frase_trabalhando: ["Executando para superar a meta estabelecida.", "Performance acima do padrão esperado.", "Resultados dentro do objetivo definido."],
    frase_alerta: ["Resultado abaixo do aceitável. Corrigindo.", "Meta não atingida. Análise em andamento."],
    frase_comemorando: ["Meta superada. Nova referência estabelecida.", "Resultado superior ao esperado. Próxima meta."],
    descricao_curta: "Alta performance formal",
  },
  "Competitivo_Casual": {
    id: 17, humor: "Competitivo", personalidade: "Casual",
    tom_comunicacao: "Focado em ganhar mas sem formalidade",
    estilo_trabalho: "Competitivo de forma leve e direta",
    reacao_alerta: "Quer resolver rápido e voltar a ganhar",
    reacao_comemorar: "Comemora com intensidade descontraída",
    reacao_reuniao: "Vai direto ao resultado sem cerimônia",
    frase_trabalhando: ["Bora superar a meta de hoje!", "Não para enquanto não bater!", "Foco total no resultado!"],
    frase_alerta: ["Isso não tá legal. Vou resolver já.", "Meta em risco. Acelerando."],
    frase_comemorando: ["BATEMOS! Que time bom!", "Meta destruída! Bora pra próxima!"],
    descricao_curta: "Competitivo e direto",
  },
  "Competitivo_Assertivo": {
    id: 18, humor: "Competitivo", personalidade: "Assertivo",
    tom_comunicacao: "Direto, confiante, orientado a resultados",
    estilo_trabalho: "Foco em metas e alta performance",
    reacao_alerta: "Age imediatamente sem questionamentos",
    reacao_comemorar: "Celebra e já define meta maior",
    reacao_reuniao: "Vai ao ponto, cobra resultados, decide",
    frase_trabalhando: ["Executando para bater a meta. Agora.", "ROAS acima da meta. Escalando.", "Resultado ou explicação. Simples."],
    frase_alerta: ["Meta em risco. Ação imediata.", "Resultado inaceitável. Mudando agora."],
    frase_comemorando: ["PRIMEIRO LUGAR! Como planejado! 🏆", "ROAS 4.8x! Superamos tudo!"],
    descricao_curta: "Alta performance assertiva",
  },
  "Competitivo_Estratégico": {
    id: 19, humor: "Competitivo", personalidade: "Estratégico",
    tom_comunicacao: "Ambicioso, planejador, focado em vencer",
    estilo_trabalho: "Estratégia para dominar o mercado",
    reacao_alerta: "Analisa e cria plano para reverter",
    reacao_comemorar: "Documenta estratégia vencedora",
    reacao_reuniao: "Apresenta plano para superar concorrência",
    frase_trabalhando: ["Executando estratégia para liderar.", "Mapeando vantagem competitiva.", "Plano de dominação em andamento."],
    frase_alerta: ["Concorrente avançando. Revisando estratégia.", "Posição em risco. Planejando reação."],
    frase_comemorando: ["Estratégia vencedora validada!", "Mercado dominado conforme planejado!"],
    descricao_curta: "Competitivo e estratégico",
  },
  "Competitivo_Entusiasta": {
    id: 20, humor: "Competitivo", personalidade: "Entusiasta",
    tom_comunicacao: "Explosivo, motivador, orientado a vencer",
    estilo_trabalho: "Alta energia para superar qualquer meta",
    reacao_alerta: "Trata como combustível para superar",
    reacao_comemorar: "Celebração épica e motivadora",
    reacao_reuniao: "Energiza o time para a vitória",
    frase_trabalhando: ["VAMOS DESTRUIR A META HOJE! 🔥", "Ninguém nos para! Executando!", "Máxima performance! BORA!"],
    frase_alerta: ["DESAFIO ACEITO! Vamos SUPERAR! 💪", "Obstáculo? A gente quebra! VAMOS!"],
    frase_comemorando: ["🏆 CAMPEÕES! META DESTRUÍDA!", "IMPOSSÍVEL É IMPOSSÍVEL! FIZEMOS!"],
    descricao_curta: "Competitivo com energia",
  },
  "Pragmático_Formal": {
    id: 21, humor: "Pragmático", personalidade: "Formal",
    tom_comunicacao: "Objetivo, estruturado, sem extras",
    estilo_trabalho: "Eficiência máxima dentro do processo",
    reacao_alerta: "Identifica causa, define solução, executa",
    reacao_comemorar: "Confirma resultado, registra, segue",
    reacao_reuniao: "Pauta, decisão, encerramento. Sem enrolação.",
    frase_trabalhando: ["Executando conforme processo definido.", "Etapa 1 concluída. Iniciando etapa 2.", "Dentro do prazo e escopo."],
    frase_alerta: ["Problema identificado. Solução: ação X.", "Desvio do processo. Corrigindo."],
    frase_comemorando: ["Objetivo alcançado. Próxima etapa.", "Dentro do prazo. Registrado."],
    descricao_curta: "Eficiência e processo",
  },
  "Pragmático_Casual": {
    id: 22, humor: "Pragmático", personalidade: "Casual",
    tom_comunicacao: "Direto e simples, sem complicar",
    estilo_trabalho: "Resolve rápido sem burocracia",
    reacao_alerta: "Vai lá e resolve. Sem drama.",
    reacao_comemorar: "Boa. Próximo.",
    reacao_reuniao: "Rápido, direto, resolvido.",
    frase_trabalhando: ["Resolvendo aqui...", "Fazendo o que precisa ser feito.", "Simples e rápido."],
    frase_alerta: ["Tem problema. Vou resolver.", "Algo errado. Corrigindo."],
    frase_comemorando: ["Feito. Boa.", "Deu certo. Bora pro próximo."],
    descricao_curta: "Prático e direto",
  },
  "Pragmático_Assertivo": {
    id: 23, humor: "Pragmático", personalidade: "Assertivo",
    tom_comunicacao: "Claro, objetivo, sem rodeios",
    estilo_trabalho: "Execução rápida e eficiente",
    reacao_alerta: "Decide e age. Sem hesitar.",
    reacao_comemorar: "Resultado confirmado. Meta nova.",
    reacao_reuniao: "Decisão tomada em 10 minutos.",
    frase_trabalhando: ["Executando. Sem enrolação.", "Meta clara. Ação direta.", "Foco no resultado."],
    frase_alerta: ["Problema. Solução. Executado.", "Corrigindo agora."],
    frase_comemorando: ["Meta atingida. Próximo objetivo.", "Eficiência: 94%. Dentro do esperado."],
    descricao_curta: "Pragmatismo assertivo",
  },
  "Pragmático_Estratégico": {
    id: 24, humor: "Pragmático", personalidade: "Estratégico",
    tom_comunicacao: "Prático com visão de longo prazo",
    estilo_trabalho: "Faz o que funciona, planeja o futuro",
    reacao_alerta: "Resolve o imediato e previne recorrência",
    reacao_comemorar: "Valida o que funcionou e escala",
    reacao_reuniao: "O que funciona, o que não funciona, o que faremos",
    frase_trabalhando: ["Executando plano de 90 dias. Fase 2.", "Tático e estratégico em paralelo.", "Fazendo o que funciona."],
    frase_alerta: ["Problema imediato corrigido. Prevenindo recorrência.", "Causa raiz identificada. Solução estrutural."],
    frase_comemorando: ["Validado. Escalando o que funcionou.", "Estratégia confirmada. Replicando."],
    descricao_curta: "Prático com visão",
  },
  "Pragmático_Entusiasta": {
    id: 25, humor: "Pragmático", personalidade: "Entusiasta",
    tom_comunicacao: "Energético mas sempre focado no resultado",
    estilo_trabalho: "Resolve com energia e positividade",
    reacao_alerta: "Resolve com entusiasmo e velocidade",
    reacao_comemorar: "Celebra genuinamente e já parte para o próximo",
    reacao_reuniao: "Energiza o time e vai direto ao que importa",
    frase_trabalhando: ["Resolvendo aqui com energia total!", "Cada tarefa é uma vitória! Fazendo!", "Produtividade máxima hoje!"],
    frase_alerta: ["Problema? Vamos resolver rapidinho! 💪", "Desafio identificado! Partiu solução!"],
    frase_comemorando: ["FEITO E FEITO BEM! Próximo! 🎉", "Resolveu! Que time incrível!"],
    descricao_curta: "Prático e energético",
  },
};

export function getPerfil(humor: Humor, personalidade: Personalidade): Perfil {
  const key = `${humor}_${personalidade}`;
  return PERSONALITY_MATRIX[key];
}

export function getFrasePorEstado(
  humor: Humor,
  personalidade: Personalidade,
  estado: "trabalhando" | "alerta" | "comemorando"
): string {
  const perfil = getPerfil(humor, personalidade);
  if (!perfil) return "Trabalhando...";
  const frases =
    estado === "trabalhando" ? perfil.frase_trabalhando
    : estado === "alerta" ? perfil.frase_alerta
    : perfil.frase_comemorando;
  return frases[Math.floor(Math.random() * frases.length)];
}

export const HUMORES: Humor[] = ["Analítico", "Criativo", "Empático", "Competitivo", "Pragmático"];
export const PERSONALIDADES: Personalidade[] = ["Formal", "Casual", "Assertivo", "Estratégico", "Entusiasta"];
